### ISSUE TITLE
Linux shader compilation

### ISSUE THREAD

**Issue by SlavSquatSuperstar** [SlavSquatSuperstar/mayonez-engine-2d#16]
- Make sure the program can run on Linux
- ~~Issue: .glsl shaders cannot compile on Linux~~
- Fix: Shader compilation can be changed by changing GLSL version to >400

**Comment by qgt7zm** [comment]
OpenGL Versions
- Latest version: 4.6 (GLSL 460)
- Max macOS supported: 4.1 (GLSL 410)

macOS ARM Issues
- Cannot cast floats to ints to use in switch statement; if/elses must be used instead

Source: https://reddit.com/r/opengl/comments/oc8ec1/opengl_on_mac

**Comment by SlavSquatSuperstar** [comment]
- Fix: Shader compilation can be changed by changing GLSL version to >400
- Issue: Deleting textures using GL11C class causes JVM errors
